name: 'Create Resyntax Pull Request'
description: 'Run Resyntax on the repository and gather its suggestions into a pull request'
branding:
  icon: 'git-pull-request'
  color: 'red'
inputs:
  private-key:
    description: 'A private key for the Resyntax CI GitHub App.'
    required: true
  max-fixes:
    description: 'The maximum number of suggested fixes to apply.'
    required: false
    default: '20'
  max-modified-files:
    description: 'The maximum number of files to modify.'
    required: false
    default: '10'
  max-modified-lines:
    description: 'The maximum number of lines to modify.'
    required: false
    default: '300'
  max-pass-count:
    description: 'The maximum number of passes to perform on the same files.'
    required: false
    default: '10'
runs:
  using: "composite"
  steps:
    - name: Install Resyntax
      run: raco pkg install --auto resyntax
      shell: bash
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: 999945
        private-key: ${{ inputs.private-key }}
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
    - name: Configure Git committer
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ steps.generate-token.outputs.token }}
        script: |
          await exec.exec('git config user.name "${{ steps.generate-token.outputs.app-slug }}[bot]"');
          await exec.exec('git config user.email "${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com"');
    - name: Create a new branch
      run: git checkout -b autofix-${{ github.run_number }}-${{ github.run_attempt }}
      shell: bash
    - name: Run Resyntax
      run: |
        racket -l- resyntax/cli fix \
          --directory . \
          --max-fixes ${{ inputs.max-fixes }} \
          --max-modified-files ${{ inputs.max-modified-files }} \
          --max-modified-lines ${{ inputs.max-modified-lines }} \
          --max-pass-count ${{ inputs.max-pass-count }} \
          --output-as-commit-message \
          --create-multiple-commits \
          >> /tmp/resyntax-output.txt
      shell: bash
    - name: Create pull request
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ steps.generate-token.outputs.token }}
        script: |
          const { readFile, writeFile } = require('fs/promises');
          const commitMessageBody = await readFile('/tmp/resyntax-output.txt', { encoding: 'utf8' });
          const commitMessageTitle = "Automated Resyntax fixes";
          await exec.exec('git push --set-upstream origin autofix-${{ github.run_number }}-${{ github.run_attempt }}');
          await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: commitMessageTitle,
            head: "autofix-${{ github.run_number }}-${{ github.run_attempt }}",
            base: "${{ github.event.repository.default_branch }}",
            body: commitMessageBody,
            maintainer_can_modify: true,
          });
